config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'

  resources :schools do
    resources :students
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students, dependent: :destroy

  validates :capacity, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 52000 }
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :principal, presence: true
  validates :capacity, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, :student_number, :gpa, presence: true
  validates :name, uniqueness: true
  validates :student_number, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10000}

  belongs_to :school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # TODO: add this back in later when things are working again
  #before_action :load_school, only: %i(show edit update destroy)

  def index
    @schools = School.all
  end

  def show
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    if @school.save
      redirect_to(schools_path(@school), notice: "School added")
    else
      flash[:alert] = "Error saving school"
      render(:new)
    end
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    if @school.update(school_params)
      redirect_to(schools_path(@school), notice: "School updated")
    else
      flash[:alert] = "Error saving school"
      render(:edit)
    end
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy
    redirect_to(schools_path, notice: "School deleted")
  end

  private

  def load_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :address, :principal, :capacity, :private_school)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_school
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /schools/1/students
  def index
    @students = @students.all
  end

  # GET /schools/1/students/1
  def show
  end

  # GET /schools/1/students/new
  def new
    @student = @school.students.new
  end

  # GET /schools/1/students/1/edit
  def edit
  end

  # POST /schools/1/students
  def create
    @student = @school.student.new(student_params)

    if @student.save
      redirect_to @student, notice: 'Student is created'
    else
      render :new
    end
  end

  # PUT/PATCH /schools/1/students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student is updated'
    else
      render :edit
    end
  end

  # DELETE /schools/1/students/1
  def destroy
    @student.destroy
    redirect_to school_students_path(@school), notice: 'School is deleted'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:school_id])
    end

    def set_student
      @student = @school.students.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:name, :student_number, :gpa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolSpecs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <% if notice %>
  <div class="flash-notice"><%= notice %></div>
  <% end %> <% if alert %>
  <div class="flash-alert"><%= alert %></div> <% end %>
  <%= yield %>
  </body>
</html>

app/views/schools/_schools.html.erb
<% schools.each do |school| %>
    <div class="school-card">
      <p><%= school.name %></p>
      <p><%= school.address %></p>
      <p><%= school.principal %></p>
      <p><%= school.capacity %></p>
      <p><%= school.private_school %></p>
    </div>
  <% end %>

app/views/schools/_schools_form.html.erb
<div>
  <%= f.label(:name) %><br>
  <%= f.text_field(:name) %>
</div>
<div>
  <%= f.label(:address) %><br>
  <%= f.text_area(:address) %>
</div>
<div>
  <%= f.label(:principal) %><br>
  <%= f.text_field(:principal) %>
</div>
<div>
  <%= f.label(:capacity) %><br>
  <%= f.number_field(:capacity) %>
</div>
<div>
  <%= f.label(:private_school) %>
  <%= f.check_box(:private_school) %>
</div>

app/views/schools/edit.html.erb
<h1>Schools</h1>

<%= form_for(@school) do |f| %>
  <%= render("schools_form", f: f) %>
  <%= f.submit("Save") %>
<% end %>

app/views/schools/index.html.erb
<h1>Schools</h1>
<%= link_to("Add School", new_school_path) %>

<ul>
<% @schools.each do |school| %>
  <li>
    <%= school.name %>
    - 
    <%= link_to("edit", edit_school_path(school.id)) %>
    -
    <%= link_to("delete", school_path(school.id), method: :delete, data: {confirm: "Delete?"}) %>
  </li>
<% end %>
</ul>

app/views/schools/new.html.erb
<h1>Schools</h1>
<%= form_for(@school) do |f| %>
  <%= render("schools_form", f: f) %>
  <%= f.submit("Save") %>
<% end %>

app/views/schools/show.html.erb
<h1>Schools</h1>
<%= link_to("Add student", new_school_student_path(@school)) %>

<ul>
  <% @school.students.each do |student| %>
    <li>
      <%= student.name %>
      - <%= link_to("edit", edit_school_student_path(@school, student)) %>
        <%= link_to("delete", school_student_path(@school, student), method: :delete, data: {confirm: "Delete?"}) %>
    </li>
  <% end %>
</ul>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

app/views/students/new.html.erb
<h1>Students#new</h1>
<p>Find me in app/views/students/new.html.erb</p>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>